executable      = $ENV(HOMEDIR)/condor/limits/condor_executable.sh
output          = $ENV(HOMEDIR)/condor/limits/limits_logs/job.$(ClusterId).$(ProcId).out
error           = $ENV(HOMEDIR)/condor/limits/limits_logs/job.$(ClusterId).$(ProcId).err
log             = $ENV(HOMEDIR)/condor/limits/limits_logs/job.$(ClusterId).$(ProcId).log

getenv = True
+JobFlavour = "workday"
+DESIRED_Sites = "T2_US_UCSD"
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:x86_64"
transfer_input_files = $ENV(HOMEDIR)/package_$ENV(LABEL).tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
x509userproxy=$ENV(X509_USER_PROXY)
use_x509userproxy = True
JobBatchName = "$ENV(LABEL)"

queue arguments from (
##
### ScenarioB1
##
#$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 4.000_M1.330 0.10
#$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 4.000_M1.330 1.00
#$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 4.000_M1.330 10.00
#$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 4.000_M1.330 100.00
##
$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 5.000_M2.400 0.10
$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 5.000_M2.400 1.00
$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 5.000_M2.400 10.00
$ENV(SCOUTINGSNTINPUTDIRLIM) $ENV(SCOUTINGSNTOUTPUTDIRLIM) ScenarioB1 asymptotic $ENV(PERIOD) 5.000_M2.400 100.00
##
)